export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const apiURL = 'http://localhost:8080';

export const CHANGE_CELL_VALUE = 'CHANGE_CELL_VALUE';
export const CHANGE_DELTA_MINUS_VALUE = 'CHANGE_DELTA_PLUS_VALUE';
export const CHANGE_DELTA_PLUS_VALUE = 'CHANGE_DELTA_MINUS_VALUE';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CHANGE_NUM_OF_COLUMNS = 'CHANGE_NUM_OF_COLUMNS';
export const CHANGE_NUM_OF_ROWS = 'CHANGE_NUM_OF_ROWS';
export const CHANGE_NUM_OF_COLUMNS_DELTA_MINUS =
  'CHANGE_NUM_OF_COLUMNS_DELTA_MINUS';
export const CHANGE_NUM_OF_ROWS_DELTA_MINUS = 'CHANGE_NUM_OF_ROWS_DELTA_MINUS';
export const CHANGE_NUM_OF_COLUMNS_DELTA_PLUS =
  'CHANGE_NUM_OF_COLUMNS_DELTA_PLUS';
export const CHANGE_NUM_OF_ROWS_DELTA_PLUS = 'CHANGE_NUM_OF_ROWS_DELTA_PLUS';

export const CHANGE_FUZZY = 'CHANGE_FUZZY';
